// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwIsRqsdeGsjBGLOZwGyKwCkdwIaEbbus',
    appId: '1:115732873363:web:1d58ea4b0d3738c331cd66',
    messagingSenderId: '115732873363',
    projectId: 'tomatogame-79380',
    authDomain: 'tomatogame-79380.firebaseapp.com',
    storageBucket: 'tomatogame-79380.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU19uy1fjWqNkhIH3hqFsqJKe0MmbVNV0',
    appId: '1:115732873363:android:740b88773dc4879531cd66',
    messagingSenderId: '115732873363',
    projectId: 'tomatogame-79380',
    storageBucket: 'tomatogame-79380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdX0q_1vP_NEZpoVqJSUMpMctLXmQXpAc',
    appId: '1:115732873363:ios:ab3155800f1a81e431cd66',
    messagingSenderId: '115732873363',
    projectId: 'tomatogame-79380',
    storageBucket: 'tomatogame-79380.appspot.com',
    iosBundleId: 'com.example.tomatoGame',
  );
}
